# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Matthew Wyskiel
email: mwwyskiel@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Software Developer, Music Enthusiast, News Junkie.
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://mattwyskiel.com' # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: mattwyskiel
github_username: mattwyskiel

defaults:
  - scope:
      path: ''
    values:
      image: /assets/images/default_article_image.png

author:
  twitter: mattwyskiel

logo: /assets/images/default_article_image.png

twitter:
  username: mattwyskiel
  card: summary

social:
  name: Matthew Wyskiel
  liniks:
    - https://twitter.com/MattWyskiel
    - https://www.linkedin.com/in/mattwyskiel
    - https://github.com/mattwyskiel
    - https://instagram.com/mattwyskiel

google_analytics: UA-60203680-1

disqus:
  shortname: mattwyskielblog

paginate: 5
paginate_path: '/blog/:num'

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
