on:
  push:
    branches:
      - 'main'
      - 'develop'
    paths:
      - 'infra/**'
      - '.github/workflows/infra.yaml'

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Publishes this SST stack
    steps:
      - uses: actions/checkout@v3
      - id: pnpm-install
        uses: mattwyskiel/sst-node-pnpm-setup@v1
      - run: cd infra && pnpm i
        shell: bash
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::662292074719:role/whiskey-app-role
          role-session-name: sst-pnpm-workflows-sample
      - run: cd infra && pnpm sst deploy --stage dev
        shell: bash
        if: startsWith(github.ref_name, 'develop')
      - run: cd infra && pnpm sst deploy --stage prod
        shell: bash
        if: startsWith(github.ref_name, 'main')
